#' Generate a sample linelist from the observed linelist and sampled linelists
#'
#' @param count_linelist Dataframe with two variables: date_report and daily_linelist. As generated by  `linelist_from_case_counts`.
#' @param observed_linelist Dataframe with two variables: date_report and daily_observed_linelist. As generated by `split_linelist_by_day``
#' @param merge_actual_onsets Logical, defaults to `TRUE`. Should linelist onset dates be used where available?
#' @param earliest_allowed_onset A character string in the form of a date ("2020-01-01") indiciating the earliest
#' allowed onset.
#' @return Dataframe with no missing data and two variables: date_report and date_onset
#' @export
#' @importFrom dplyr left_join filter mutate select bind_rows slice
#' @importFrom data.table setkey merge.data.table fifelse
#' @importFrom purrr map2
#' @examples
#'
#'
generate_sample_linelist <- function(count_linelist = NULL, observed_linelist = NULL,
                                     merge_actual_onsets = TRUE, earliest_allowed_onset = NULL) {

  if (nrow(observed_linelist) > 0 & merge_actual_onsets) {
    data.table::setkey(count_linelist,date_report, n)
    data.table::setkey(observed_linelist,date_report, n)

    populated_linelist <- data.table::merge.data.table(count_linelist,observed_linelist, all.x = TRUE)
    populated_linelist <- populated_linelist[, date_onset := data.table::fifelse(is.na(date_onset.y),
                                                                                 date_onset.x,
                                                                                 date_onset.y)][
                                                                                   , list(date_onset,
                                                                                          date_report = date_report)]


    }else{
    populated_linelist <- count_linelist[,list(date_onset, date_report)]
  }


  if (!is.null(earliest_allowed_onset)) {
    populated_linelist <- populated_linelist[date_onset >= as.Date(earliest_allowed_onset)]

  }

  return(populated_linelist)
}
