#' Sample Onset Dates for Cases missing them
#'
#' @param linelist Dataframe with two variables: date_report and date_onset. As generated by  `generate_pseudo_linelist`.
#' @param earliest_allowed_onset A character string in the form of a date ("2020-01-01") indiciating the earliest
#' allowed onset.
#' @param delay_fn A sampling funtion that takes a single numeric argument and returns a vector of
#' numeric samples this long.
#' @return Dataframe with no missing data and two variables: date_report and date_onset
#' @export
#' @importFrom data.table fifelse
#' @importFrom purrr map2
#' @importFrom data.table copy
#' @examples
#'
#'
sample_delay <- function(linelist = NULL, delay_fn = NULL, earliest_allowed_onset = NULL) {


## Sample onsets for all data at once
## If missing an actual onset then use the sampled version
## Select only onsets and report dates
    out <- data.table::copy(linelist)
    
    out <- out[, date_onset_sample := date_report - lubridate::days(delay_fn(.N)),][
      is.na(date_onset), date_onset := date_onset_sample][,list(date_onset, date_report)]
                                                                                
  if (!is.null(earliest_allowed_onset)) {
    out <- out[date_onset >= as.Date(earliest_allowed_onset)]

  }

  return(out)
}
 